BDBundle\Entity\Categorias:
    type: entity
    table: categorias
    id:
        categoriaid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombreCategoria:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
                default: ''
            column: nombre_categoria
        descripcion:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        imagen:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
    lifecycleCallbacks: {  }
