frontend:
    resource: "@FrontendBundle/Resources/config/routing.yml"
    prefix:   /

bd:
    resource: "@BDBundle/Resources/config/routing.yml"
    prefix:   /bd

app_default:
    resource: "@AppBundle/Resources/config/default.yml"
    prefix:   /admin

app_ayuda:
        resource: "@FrontendBundle/Resources/config/ayuda.yml"
        prefix:   /ayuda

app_libros:
    resource: "@FrontendBundle/Resources/config/libros.yml"
    prefix:   /libros