frontend_ayuda_formaspago:
    path: /formaspago
    defaults: { _controller: FrontendBundle:Ayuda:formaspago }

frontend_ayuda_instalaciones:
    path: /instalaciones
    defaults: { _controller: FrontendBundle:Ayuda:instalaciones }